apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: app
    image: gcr.io/devops-courses-419309/demo:v1.0.0
    ports:
    - containerPort: 8080
      name: http
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 2
      failureThreshold: 3
      successThreshold: 1
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
  volumes:
  - name: data
    hostPath:
      path: /var/lib/app
      type: Directory
  volumeMounts:
  - name: data
    mountPath: /data
