apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
  labels:
    app: demo
spec:
  containers:
    - name: app
      image: gcr.io/devops-courses-419309/demo:v1.0.0
      ports:
        - containerPort: 8000
          name: http
        - containerPort: 8080
          name: http
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
